core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

ek_homepage:
    resource: "@EKHomepageBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
